### ISSUE TITLE
Running step four multiple times (!)

### ISSUE THREAD

**Issue by jmandel** [microsoft-healthcare-madison/argonaut-subscription-client-ui#11]
I'm slightly surprised by what happens if I hit:

![image](https://user-images.githubusercontent.com/313089/63050231-37b27d80-bea0-11e9-90a8-95407afc78d9.png)

more than one time. I mean, at that point a single trigger causes multiple simultaneous results to arrive in the Step 7 box. We might want to provide some guardrails that prevent creation of multiple subscriptions in the same flow, so the steps are more linear... and then provide a tab with more of a free-for-all playground that exposes all the options for folks to go nuts.

**Comment by jmandel** [comment]
Or alternatively we could update the notifications in:
![image](https://user-images.githubusercontent.com/313089/63050381-937d0680-bea0-11e9-9c20-2203cdf4b4c9.png)

at least to label as "notification" rather than "event" because one item in step 7 may correspond to multiple subscription "events" (e.g., if Bundle.entry.length > 1).

**Comment by GinoCanessa** [comment]
Fixed multiple notifications when the UI stopped allowing multiple subscriptions in the workflow (83a170b0f1f0a781e135880f7b5a5732af2f80e1).
Fixed labeling in UI to be "Notification" (acbc1914b024f4828f75ec82edc3bf6a748f9f8b)
