### ISSUE TITLE
security alert discovered in a dependency

### ISSUE THREAD

**Issue by barabo** [microsoft-healthcare-madison/argonaut-subscription-client-ui#12]
https://github.com/microsoft-healthcare-madison/argonaut-subscription-client-ui/network/alerts

I'm not sure if this is of critical importance, but there is a big scary warning on the github landing page for this project because of the detected vulnerability.  It would probably be good to remedy it, if possible.

**Comment by GinoCanessa** [comment]
Should be cleared, added a peer dependency in the root of the project to ensure that a lower version of lodash is never used.

**Comment by jmandel** [comment]
(Do note that the big scary warnings aren't visible to the public, just as an FYI. They still deserve attention of course :))
