### ISSUE TITLE
Validate endpoints or don't give user choices

### ISSUE THREAD

**Issue by jmandel** [microsoft-healthcare-madison/argonaut-subscription-client-ui#14]
Right now a stubborn user (like me) can do silly stuff like:

![image](https://user-images.githubusercontent.com/313089/63125025-423d4780-bf72-11e9-93a2-854f67bcc4a4.png)

It'd be good to validate these, or (I think better still) just user a server-generated name. We might even run this step automatically, without making the user click a button at all if there's no decisions to make.

**Comment by GinoCanessa** [comment]
Removed the text input and made the step automatically trigger when a patient is selected.

Commit: 83a170b0f1f0a781e135880f7b5a5732af2f80e1
