### ISSUE TITLE
Alternate names for "client host"

### ISSUE THREAD

**Issue by jmandel** [microsoft-healthcare-madison/argonaut-subscription-client-ui#4]
I think "client host" may end up causing confusion, though I'm not sure another term will help ;-)

* Endpoint Manager
* Message Router?
* Client Gateway?

I kind of like "Endpoint Manager" as a standalone thing -- but this depends on what other jobs this component will have over time. (Like, will trigger management live in the browser, or in the host?)

**Comment by GinoCanessa** [comment]
Never came up with a better name and I feel like changing it now would be confusing.
