### ISSUE TITLE
Account of presence/absence of trailing slashes in user-entered URLs

### ISSUE THREAD

**Issue by jmandel** [microsoft-healthcare-madison/argonaut-subscription-client-ui#8]
For a FHIR server `https://server.subscriptions.argo.run/baseR4` fails while `https://server.subscriptions.argo.run/baseR4/` succeeds. Desired state: UI should tolerate presence/absence of trailing slashes for user-entered URLs.

**Comment by GinoCanessa** [comment]
UI now uses URL structures to ensure all paths are concatenated properly.
