### ISSUE TITLE
Allow build-time variables to control default client + server URLs

### ISSUE THREAD

**Issue by jmandel** [microsoft-healthcare-madison/argonaut-subscription-client-ui#9]
e.g. `npm run build` should use something like https://medium.com/@tacomanator/environments-with-create-react-app-7b645312c09d to allow env vars like `REACT_APP_DEFAULT_FHIR_SERVER_URL` and `REACT_APP_DEFAULT_CLIENT_HOST_URL` to control this.

**Comment by GinoCanessa** [comment]
Added src/public/env.js (loaded in src/public/index.html prior to the app) which sets properties on window._env.  Updated the infrastructure project to generate this file during container initialization based on a configMap.
